version: "3.8"
services:
  app:
    build:
      args:
        user: '1012'
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: posyandu
    container_name: posyandu-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - posyandu

  db:
    image: mysql:8.0
    container_name: posyandu-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: posyandu
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - posyandu

  nginx:
    image: nginx:alpine
    container_name: posyandu-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - posyandu

networks:
  posyandu:
    driver: bridge
